name: Workspace cleanup
description: Action used for cleaning a given directory when invoked

runs:
  using: "composite"
  steps:
    - name: Workspace cleanup
      shell: sh
      run: |
          rm -rf ./* || true
          rm -rf ./.??* || true
