name: Workspace cleanup
description: Action used for cleaning a given directory when invoked and optionally after the job has completed

inputs:
  path:
    description: Path to purge, defaults to current directory
    required: false
    default: .
  post:
    description: Whether or not to clean the path also after the job has completed
    required: false
    default: true
  
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
