name: units-test
on:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:

  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  test:
    runs-on: ubuntu-latest

    env:
      SAMPLES: .test

    steps:

    - uses: actions/checkout@v2

    - name: Prepare ascii and binary test files
      run: |
        for i in {1..5}; do mkdir -p $SAMPLES/$i $SAMPLES/.${i}; done
        find $SAMPLES -type d | while read d; do echo "This is directory $d" >$d/dir; cp -a $d/dir $d/.dir; done
        zip -r $SAMPLES/source.zip $SAMPLES

    - name: Cleanup
      uses: ./
      with:
        path: ${{ env.SAMPLES }}

    - name: Count test files
      run: |
        [ $(find ${{ env.SAMPLES }} -mindepth 1 | wc -l) -eq 0 ]
